version: '3.9'
services:
  backend:
    build: ./backend
    environment:
      - PORT=3000
      - DB_PATH=/data/places.db
      - GOOGLE_CSE_KEY=${GOOGLE_CSE_KEY}
      - GOOGLE_CSE_CX=${GOOGLE_CSE_CX}
    volumes:
      - ./data:/data
    ports:
      - "3000:3000"
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:80"

